FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Target the worker entry point
RUN CGO_ENABLED=0 GOOS=linux go build -o /simulation-worker ./cmd/worker/main.go

FROM alpine:latest
WORKDIR /
COPY --from=builder /simulation-worker /simulation-worker
ENTRYPOINT ["/simulation-worker"]